### PR TITLE
Switched to CoordinatorLayout from SwipeToRefresh, added Floating Action Button

### PR DESCRIPTION
**Pull request by grubdragon**
This change is [Reviewable](https://reviewable.io/reviews/unstablebrainiac/iitb-app/30)

### CODE REVIEW

**Comment by unstablebrainiac** [comment]
You don't switch to Coordinator layout, you add it without changing the Swipe to Refresh functionality

**Comment by grubdragon** [comment]
Didn't you tell me to do this -_-

**Comment by unstablebrainiac** [comment]
Fix this.

**Comment by grubdragon** [comment]
Tell me exactly what you need, I'll fix it

**Pull request closed without merging**
